# Generated by Django 5.1.6 on 2025-04-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
