# Generated by Django 5.1.6 on 2025-04-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_populate_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
