# Generated by Django 5.1.6 on 2025-04-14 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0004_alter_notification_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_email',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General Notification'), ('community_invite', 'Community Invitation'), ('community_join_request', 'Community Join Request'), ('community_join_approved', 'Community Join Approved'), ('community_join_rejected', 'Community Join Rejected'), ('community_new_post', 'New Community Post'), ('community_post_updated', 'Community Post Updated'), ('community_event', 'Community Event'), ('post_upvote', 'Post Upvote'), ('comment_upvote', 'Comment Upvote'), ('comment_reply', 'Comment Reply'), ('mention', 'Mention'), ('admin_alert', 'Admin Alert')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_invites', models.BooleanField(default=True)),
                ('community_join_requests', models.BooleanField(default=True)),
                ('community_updates', models.BooleanField(default=True)),
                ('community_new_posts', models.BooleanField(default=True)),
                ('community_post_updates', models.BooleanField(default=True)),
                ('post_upvotes', models.BooleanField(default=True)),
                ('comment_upvotes', models.BooleanField(default=True)),
                ('comment_replies', models.BooleanField(default=True)),
                ('mention_notifications', models.BooleanField(default=True)),
                ('email_community_invites', models.BooleanField(default=True)),
                ('email_community_updates', models.BooleanField(default=False)),
                ('email_engagement', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
