# Generated by Django 5.2 on 2025-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Not added', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Not added'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='Not added', max_length=15),
        ),
    ]
