# Generated by Django 5.2 on 2025-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to='users/profile_photos/'),
        ),
    ]
